name: styleproc_element
author: Salomon BRYS <salomon.brys@gmail.com>
version: 0.2.0
homepage: https://github.com/SalomonBrys/dart-styleproc-element
description: Easily integrates any css processor inside polymer.dart
documentation: https://github.com/SalomonBrys/dart-styleproc-element
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  polymer: '>=0.9.0 <0.10.0'
